image: 'proboci/ubuntu-14.04-lamp-beta'
steps:
  - name: Setup Drupal
    plugin: Drupal
    makeFile: build-bear.make
    runInstall: bear
  - name: Get login link
    command: 'drush --root=/var/www/html uli'
 #- name: Run behat tests
 #  command: 'cd /var/www/bear/webroot/profiles/bear/tests ; composer install ; ./bin/behat --profile probo --tags "~@javascript"'
