assets:
  - database.sql
image: 'proboci/ubuntu-14.04-lamp-beta'
steps:
  - name: Setup Drupal
    plugin: Drupal
    makeFile: build-bear.make
    #database: database.sql
    profileName: bear
    runInstall: true
  - name: Get login link
    command: 'drush uli'
